POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "My Product",
  "price": 100
}

###
GET http://localhost:8000/products/1ebc61b4-9c64-4d1d-b9c5-32468b99c519
Content-Type: application/json

###
PUT http://localhost:8000/products/1ebc61b4-9c64-4d1d-b9c5-32468b99c519
Content-Type: application/json

{
  "name": "My Updated Product",
  "price": 200
}